version: '3.8'
services:
  # Simple API server
  api:
    build: .
    command: python3 simple_api.py
    ports:
      - "8000:8000"
    restart: unless-stopped

  # Demo blockchain OS (runs demonstrations)
  blockchain:
    build: .
    command: python3 ubuntu_blockchain_os.py
    restart: unless-stopped

  # Web interface
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./web-interface.html:/usr/share/nginx/html/index.html:ro
    restart: unless-stopped

  # Native terminal interface (nginx auth protected)
  terminal:
    image: tsl0922/ttyd:latest
    command: ["ttyd", "--writable", "-p", "7681", "bash"]
    ports:
      - "8090:7681"
    restart: unless-stopped
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - TERM=xterm-256color
