
version: '3'
services:
  substrate-node:
    image: parity/polkadot:latest
    container_name: ubuntu-substrate
    ports:
      - "9944:9944"  # WebSocket RPC
      - "9933:9933"  # HTTP RPC
      - "30333:30333"  # P2P
    volumes:
      - ./chain-data:/data
    command: |
      --dev
      --ws-external
      --rpc-external
      --rpc-cors all
      --name UbuntuSecureNode
      --telemetry-url "wss://telemetry.polkadot.io/submit/ 0"
    environment:
      - RUST_LOG=runtime=debug
    restart: unless-stopped

  proof-generator:
    image: python:3.10-alpine
    container_name: zk-proof-gen
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "echo 'ZK Proof Generator Ready' && while true; do sleep 30; echo 'Generating hardware attestation proof...'; done"
    depends_on:
      - substrate-node
