version: '3'
services:
  app:
    image: python:3.10-alpine
    working_dir: /app
    volumes:
      - ./app.py:/app/app.py
    command: sh -c "pip install flask && python app.py"
    ports:
      - "8000:8000"
  
  web:
    image: nginx:alpine
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "8080:80"
