version: '3'
services:
  # Validator Node 1 (x86_64)
  validator-1:
    image: parity/polkadot:latest
    container_name: ubuntu-validator-1
    command: >
      --dev
      --ws-external
      --rpc-external
      --rpc-cors all
      --name validator-1
      --validator
      --port 30333
      --ws-port 9944
      --rpc-port 9933
    ports:
      - "9944:9944"  # WebSocket
      - "9933:9933"  # HTTP RPC
      - "30333:30333"  # P2P
    volumes:
      - ./chain-data-1:/data
    networks:
      - ubuntu-blockchain

  # Validator Node 2 (ARM simulated)
  validator-2:
    image: parity/polkadot:latest
    container_name: ubuntu-validator-2
    command: >
      --dev
      --ws-external
      --rpc-external
      --rpc-cors all
      --name validator-2-arm
      --validator
      --port 30334
      --ws-port 9945
      --rpc-port 9934
    ports:
      - "9945:9945"
      - "9934:9934"
      - "30334:30334"
    volumes:
      - ./chain-data-2:/data
    networks:
      - ubuntu-blockchain

  # Validator Node 3 (RISC-V simulated)
  validator-3:
    image: parity/polkadot:latest
    container_name: ubuntu-validator-3
    command: >
      --dev
      --ws-external
      --rpc-external
      --rpc-cors all
      --name validator-3-riscv
      --validator
      --port 30335
      --ws-port 9946
      --rpc-port 9935
    ports:
      - "9946:9946"
      - "9935:9935"
      - "30335:30335"
    volumes:
      - ./chain-data-3:/data
    networks:
      - ubuntu-blockchain

  # Phase 8: Stateless Boot Server
  boot-server:
    image: python:3.10
    container_name: ubuntu-boot-server
    command: python3 /app/stateless_network_boot.py
    ports:
      - "8888:8888"  # Boot server
      - "69:69/udp"   # TFTP
      - "67:67/udp"   # DHCP
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - ubuntu-blockchain
    depends_on:
      - validator-1

  # Web Interface
  web-interface:
    image: nginx:alpine
    container_name: ubuntu-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web-interface.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ubuntu-blockchain

  # IPFS for distributed storage
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ubuntu-ipfs
    ports:
      - "4001:4001"  # P2P
      - "5001:5001"  # API
      - "8080:8080"  # Gateway
    volumes:
      - ./ipfs-data:/data/ipfs
    networks:
      - ubuntu-blockchain

networks:
  ubuntu-blockchain:
    external: true
